<?php
/**
 * @file
 * Demonstrating how to implement White List IP .
 */

use Drupal\field_collection\Entity\FieldCollectionItem;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
#Attaching a library to a form 

forms are just render arrays, attaching a library works just the same.

Attaching to a render array

To attach a library to a render array (and perhaps a specific instance of a certain '#type'),

you must have access to that render array. Perhaps you're defining the render array. Perhaps you're modifying it in a hook. 

In either case, it will look somewhat like this:
*/
function ip_module_menu_local_tasks_alter(&$data, $route_name) {

// unset profile tabs from my acount user menu
  unset($data['tabs'][0]['entity.webform_submission.user']);
  unset($data['tabs'][0]['entity.user.edit_form']);

}

function ip_module_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  
  /* @var Drupal\Core\Entity\FieldableEntityInterface $entity */
  
  $formObject = $form_state->getFormObject();
  
  if ($formObject instanceof \Drupal\Core\Entity\EntityFormInterface) {
    $entity = $formObject->getEntity();
    if (
      $entity->getEntityTypeId() === 'node'
      && in_array($entity->bundle(), ['whitelistip','article'])
	   ) 
	      {  
		 //$form_state->setRedirect('user.page'); 
         //$form['#attached']['library'][] = 'changedata/whitelistip-plugin';
          }
  }
  
  
  
}